### ISSUE TITLE
Code Snippets - copying line numbers

### ISSUE THREAD

**Issue by ruheni** [prisma/web#1104]
Line numbers are included as part of the copied text when copying and pasting a snippet.

Example of a copied snippet: 
```prisma
1import { PrismaClient } from "@prisma/client"
2
3const prisma = new PrismaClient()
4
5// A `main` function so that you can use async/await
6async function main() {
7  // ... you will write your Prisma Client queries here
8}
9
10main()
11  .catch(e => {
12    throw e
13  })
14  .finally(async () => {
15    await prisma.$disconnect()
16  })
```

**Comment by nilubava** [comment]
Fixed in #1102

**Comment by AntonNiklasson** [comment]
I'm still seeing this issue. I'm currently using Safari 14.0.3. Also, the behaviour is unexpected in Firefox. I would love to get started on contributing here, let me know if I can help.
